# Define the IP addresses (Müssen lokale IP-Adressen sein)
IP_MASTER = "192.168.188.1"
IP_CLIENT1 = "192.168.188.2"
IP_CLIENT2 = "192.168.188.100" # (Power_SUPPLY)

# Define the ports
DEFAULT_PORT = 50000
CLIENT1_PORT = 50100
POWER_SUPPLY_PORT = 5025

# Define the timeouts and retries in ms
CONNECTION_TIMEOUT = 15
RESPONSE_TIMEOUT = 5
MAX_RETRIES = 3

# Define the states
INITIALIZING = 0
CHARGING = 1
EISTEST = 2
GETTESTDATA = 3

# Define the commands
GETCURRENTCHARGINGPARAMETERS = 0
GETFUTURECHARGINGPARAMETERS = 1
GETEISTESTDATA = 2

#Ladestation Parameter
BATTERY_VOLTAGE_LIMIT = 14.6
BATTERY_CURRENT_MIN = 0.5
CHARGE_CURRENT = 1
CHARGE_VOLTAGE = 14.6
CHECK_INTERVAL = 5
TIMEOUT_MINUTES = 1  
